name: Update Counter

on:
  workflow_dispatch: # Se activa manualmente o desde la API
    inputs:
      increment:
        description: "Valor para aumentar el contador"
        required: false
        default: "1"

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Increment counter
        run: |
          FILE=contador.json
          VALUE=$(jq '.count' $FILE)
          INCREMENT=${{ github.event.inputs.increment }}
          NEW_VALUE=$((VALUE + INCREMENT))
          echo "Nuevo valor: $NEW_VALUE"
          jq ".count = $NEW_VALUE" $FILE > temp.json && mv temp.json $FILE

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add counter.json
          git commit -m "Update counter to $NEW_VALUE"
          git push
